### ISSUE TITLE
Revanced 

### ISSUE THREAD

**Issue by ghost** [Unofficial-Life/revanced-gphotos-build#1]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules
![Screenshot_20240907_122259_YouTube](https://github.com/user-attachments/assets/10b71ad4-e0f4-4c97-86d2-370d10334db1)

**Comment by Unofficial-Life** [comment]
what's this about ?
mind informing a bit
