### ISSUE TITLE
Slow backups

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [Unofficial-Life/revanced-gphotos-build#2]
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

The backups are happening very slow when i try to download apks speed easily reaches 3.4 mbps but when i try to backup its like the backup speed is limitesd or server is slow anyway to fast it up unofficial life bro madat kardiyo

**Comment by XdekHckr** [comment]
Learn English

**Comment by ALMIGHTY-VC** [comment]
> Learn English

BRUH, i know this aint related to revanced but going by the backup speed my backup will never get completed 💀

**Comment by Unofficial-Life** [comment]
The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

**Comment by ALMIGHTY-VC** [comment]
> The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

Hmm my library size is less than a average phone user but the api call is definitely limited and slow so i think i will have to find some workaround if i got it will inform you Thanks bro for hearing my probleme 🤗

**Comment by ALMIGHTY-VC** [comment]
> The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

Hmm my library size is less than a average phone user but the api call is definitely limited and slow so i think i will have to find some workaround if i got it I will inform you Thanks bro for hearing my problem🤗

**Comment by ALMIGHTY-VC** [comment]
> The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

Hmm my library size is less than a average phone user but the api call is definitely limited and slow so i think i will have to find some workaround if i got it I will inform you Thanks bro for hearing my problem🤗

**Comment by ALMIGHTY-VC** [comment]
> The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

Hmm my library size is less than a average phone user but the api call is definitely limited and slow so i think i will have to find some workaround if i got it I will inform you Thanks bro for hearing my problem🤗

**Comment by ALMIGHTY-VC** [comment]
> The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size

Bro what is better then gms core or mirog re
I use microg re is this causing the slow backups

**Comment by Unofficial-Life** [comment]
Try turning on mobile data usage to unlimited or whatever you prefer also turn on roaming if needed the vids one too

**Comment by Unofficial-Life** [comment]
> > The backup speed is slow because you are using microg which already limits the API call in a way. it's expected that it would take long depending on the library size
> 
> Bro what is better then gms core or mirog re
> I use microg re is this causing the slow backups

Both should work fine no difference should be there
