### ISSUE TITLE
Doesn't save switch state to always make backup active

### ISSUE THREAD

**Issue by XdekHckr** [Unofficial-Life/revanced-gphotos-build#3]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

I use pixel 9 pro. Newest app version.
The issue is that even If I enable backup and wipe it from ram memory then it needs to be enable again or it can be fixed by: launching for first time (you will not have enabled backup) then go to home screen and click again on photos app, it will magically reappear as backup enabled...
Just look on video: 
https://github.com/user-attachments/assets/7b1f3138-a9ef-401e-aa3d-eed0b29df9fc
If you can't see difference then look at the bottom of the screen

Is there any way to fix this behaviour?

**Comment by Unofficial-Life** [comment]
It's already mentioned that you would need to select your account everytime you open the app, it should work in background even if you close it from recents until next open

**Comment by Unofficial-Life** [comment]
> If I enable backup and wipe it from ram memory then it needs to be enable again or it can be fixed by: launching for first time (you will not have enabled backup) then go to home screen and click again on photos app, it will magically reappear as backup enabled...
> Just look on video: 
> https://github.com/user-attachments/assets/7b1f3138-a9ef-401e-aa3d-eed0b29df9fc
> If you can't see difference then look at the bottom of the screen
> 
> Is there any way to fix this behaviour?

About this it's just how Google photos work, it refreshes itself even on original gphotos even if it doesn't look like it but using microg as an medium it just amplified that process to make it visible and somehow making it manual too

**Comment by XdekHckr** [comment]
> > If I enable backup and wipe it from ram memory then it needs to be enable again or it can be fixed by: launching for first time (you will not have enabled backup) then go to home screen and click again on photos app, it will magically reappear as backup enabled...
> > Just look on video:
> > https://github.com/user-attachments/assets/7b1f3138-a9ef-401e-aa3d-eed0b29df9fc
> > If you can't see difference then look at the bottom of the screen
> > Is there any way to fix this behaviour?
> 
> About this it's just how Google photos work, it refreshes itself even on original gphotos even if it doesn't look like it but using microg as an medium it just amplified that process to make it visible and somehow making it manual too

Thanks for your reply.
Yeah I figured out that even if it doesn't look like turned on, it's turned on and do backups in backgrounds. Anyway, is there any chance to fix this bug or figure out why is this doing that?

Also there are few issues. Like sky or delete blur or portret adjustment are not available, only magic ereaser is available which sucks. The other thing is that upscaling function (on pixel 9 pro) might be broken when doing backup via revanced gphotos instead of normal app, because it says that it is processing in cloud forever (while if you open this on pc upscaled video will be available to download, but the colors are faded) and in revanced photos app it says "waiting for enchanced image function to be turned on which doesn't make sense for me" and when I click on it then it says "waiting for backup to be created" but it is already created, anyway I am still testing this if there is workaround. I might just root in future after free year my subscription will be done because in this state it's just annoying and these ai features are not worth that as for now... 

Edit: I figured out that pixel creates 2 videos one cover and 2nd is main and this is high resolution and it have bad colors, so basically it is never being processed in cloud to get upscaled and get better color, idk if this is related to the thing that it detects that it is being saved by older device with unlimited storage or it's bug in revanced app)

**Comment by Unofficial-Life** [comment]
The patches are mainly made in mind for non-rooted users, so they could also somewhat benefit the loophole to get unlimited. And about the other AI features it's currently impossible to import with unlimited as the app layout and everything is spoofed to be like pixel XL. for the upscale features personally I don't have any device to check, so I can't give a definite answer whether it's the spoof or just google bug
