### ISSUE TITLE
Application stopped working 

### ISSUE THREAD

**Issue by UjjwalSharma01** [Unofficial-Life/revanced-gphotos-build#4]
Hi, the application stopped working, keeps on saying getting ready for backup for more than 20-30 mins, maybe because it is not able yo retrieve the data from google server which was already backed up

**Comment by Unofficial-Life** [comment]
It's an expected behavior already mentioned "may take time according to your library size". I can't say how long it will take as it varies per person (it took an hour for me)

**Comment by UjjwalSharma01** [comment]
> It's an expected behavior already mentioned "may take time according to your library size". I can't say how long it will take as it varies per person (it took an hour for me)

Ohh alright buddy, thanks for your clarification further i will try to work with this maybe we can find a solution together

**Comment by UjjwalSharma01** [comment]
> > It's an expected behavior already mentioned "may take time according to your library size". I can't say how long it will take as it varies per person (it took an hour for me)
> 
> Ohh alright buddy, thanks for your clarification further i will try to work with this maybe we can find a solution together

well it's been 3 hours and same situation, good work though

Edit 

found the solution

Might be a issue of gmscore 

Just reinstall that and add account 

Everything works smoothly, and backup starts within 2-3 mins

**Comment by Unofficial-Life** [comment]
yes sometimes gms doesn't work it would need an reinstall

**Comment by Bhagyarajbheesetty** [comment]
Application not working, app and gms does not open in android 15 Realme GT6T

**Comment by drooooov** [comment]
Also doesn't open on gt neo 3 android 14

**Comment by Bhagyarajbheesetty** [comment]
> Also doesn't open on gt neo 3 android 14

Yes, i have a solution, i cloned both microg and photos app, it worked, now the app is opening and working fine.
