### ISSUE TITLE
Stuck on getting ready to back up

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [Unofficial-Life/revanced-gphotos-build#5]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo
Idk why after updating my Backup is stuck on backup is on getting ready to back up
![IMG_20240922_161541](https://github.com/user-attachments/assets/86870111-ebe4-46ad-98fe-2d6298d247ba)

**Comment by Unofficial-Life** [comment]
@ALMIGHTY-VC Reinstall microg or wait for sometime as it's expected that it will scan for your Library which will take time

**Comment by ALMIGHTY-VC** [comment]
> @ALMIGHTY-VC Reinstall microg or wait for sometime as it's expected that it will scan for your Library which will take time

Okay will try and reply

**Comment by ALMIGHTY-VC** [comment]
Reinstalled microg it worked thanks a ton

**Comment by ALMIGHTY-VC** [comment]
Make a FAQ TOO sorry i didnt checkee closed requests

**Comment by Unofficial-Life** [comment]
> Make a FAQ TOO sorry i didnt checkee closed requests

will do

**Comment by ALMIGHTY-VC** [comment]
> > Make a FAQ TOO sorry i didnt checkee closed requests
> 
> will do

Now it has checked my library it knows i have 1615 photos but still stuck on getting ready to backup its frustrating and microg re and g photos vanced have no restrictions as set by me but still its stuck

**Comment by Unofficial-Life** [comment]
@ALMIGHTY-VC Are you using mobile data ? 
Tried reinstalling microg ?

**Comment by ALMIGHTY-VC** [comment]
> @ALMIGHTY-VC Are you using mobile data ? Tried reinstalling microg ?

Did both using wifi router

**Comment by ALMIGHTY-VC** [comment]
Well issue was with MICROG RE which was solved in the latest update released today by wstxda thanks for your kind cooperation.Its working now
